.TH _printf "22 Nov 2022" "3.1" "man page of _printf function"
.SH _PRINTF()

.SH NAME
.B _printf - function that produces output according to a format

.SH SYNOPSIS
.B #include "main.h"
.br
.B int _printf(const char *format, ...);

.SH DESCRIPTION

- _printf() function produces output according to the format. It uses a specific function according to receipt format in order to display the result in the correct format.

The available convertion specifiers are:

.br
%c: Prints a single character.
.br
%s: Prints a string of characters.
.br
%d: Prints integers.
.br
%i: Prints integers.
.br
%b: Prints the binary representation of an unsigned decimal.
.br
%u: Prints unsigned integers
.br
%x: Prints the hexadecial representation of an unsigned decimal in lowercase letters
.br
%X:Prints the hexadecial representation of an unsigned decimal in uppercase letters
%r: Prints a reversed string
.br
%R: Prints the Rot13 interpretation of a string

.SH RETURN
-if successful, these functions return the number of characters printed (excluding the null byte).If the null return is unsuccessful, -1 is returned.


.SH EXAMPLE
.Ip
_printf("This is a simple printf %s made in %d ", "Function", 2022);
.IP
$ "This is a simple printf Function made in 2022"
.br

.SH BUGS
No detected so far. Please report any to cestrad5@gmail.com

.SH AUTHOR
Luis Alejandro Puerta / Obed Rayo / Camilo Estrada
